FCLASS(tzcnt)
FCLASS(lzcnt)
FCLASS(popcnt)
FCLASS(rbit)
FCLASS(satadd)
FCLASS(satsub)
FCLASS(pld)
FCLASS(pdep)
FCLASS(pext)
//Shift a right by imm8 bytes while shifting in zeros, and store the results in dst.
FCLASS(byteshr128)
FCLASS(xor128)
FCLASS(and128)
FCLASS(or128)
FCLASS(loadu128)
FCLASS(loada128)
FCLASS(storeu128)
FCLASS(storea128)
